###
GET http://localhost:3000/events

###
#   @name createEvent
POST http://localhost:3000/events   
Content-Type: application/json

{
  "name": "Concerto",
  "descriprtion": "Um concerto de rock com várias bandas famosas.",
  "date": "2024-07-20T19:30:00Z",
  "price": 150
}

###
@eventId = {{ createEvent.response.body.id }}

###   
GET http://localhost:3000/events/{{ eventId }}

###
PATCH  http://localhost:3000/events/{{ eventId }} 
Content-Type: application/json

{
  "name": "Concerto de Rock",
  "descriprtion": "Um concerto de rock com várias bandas famosas.",
  "date": "2024-07-20T19:30:00Z",
  "price": 150
}

###   
DELETE  http://localhost:3000/events/{{eventId}}